<h1>Numpy Revision</h1>

In [3]:
import numpy as np

# Data types - Important to understand implications to ensure accurate results

# Valid types: np.bool, np.int8, np.int16, np.uint8, np.uint16, np.float32, etc.

arr = np.array([96, 81, 84, 73, 22], dtype=np.int8)
print(arr)
print(arr.dtype)

[96 81 84 73 22]
int8


In [9]:
import numpy as np

arr = np.array([1.5, 2.2, 3.7, 4.3, 5.1]) # Defaults to float64
print(arr)
print(arr.dtype)

[1.5 2.2 3.7 4.3 5.1]
float64


In [10]:
import numpy as np

arr = np.array([1.5, 2.2, 3.7, 4.3, 5.1]) # Defaults to float64
arr_int = arr.astype(np.int16) # Truncates floating values to integers
print(arr_int.dtype)
print(arr_int)

int16
[1 2 3 4 5]


In [13]:
# Core functions - data types

import numpy as np

arr_zeros = np.zeros(10)
print(arr_zeros)

arr_ones = np.ones(10)
print(arr_ones)

arr_ones_as_int64 = np.ones(10).astype(np.int64)
print(arr_ones_as_int64)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


In [18]:
# Core-functions - Creating and reshaping arrays

arr = np.arange(10)
print(arr)

# Returns the array reorganised as a 5x2 matrix.
arr_5by2 = arr.reshape( (5,2) )
# Arithmetic Operators and Broadcasting
print(arr_5by2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [32]:
# Broadcasting

import numpy as np

# Functions can be applied element-wise to arrays with the same shape (broadbasting)
arr1 = np.array([1, 2, 3, 4, 5])
print("Array 1")
print(arr1)

print("Array 2")
arr2 = np.array([2, 4, 5, 6, 8])
print(arr2)

print("\nSum")
arr_sum = arr1 + arr2
print(arr_sum)

print("\nDifference")
arr_diff = arr2 - arr1
print(arr_diff)

Array 1
[1 2 3 4 5]
Array 2
[2 4 5 6 8]

Sum
[ 3  6  8 10 13]

Difference
[1 2 2 2 3]


In [34]:
# Arithmetic operators - scalar multiplcation

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

arr_div_2 = arr / 2.0
print(arr_div_2)

[1 2 3 4 5]
[0.5 1.  1.5 2.  2.5]


In [36]:
# Comparison operators return boolean arrays reflecting the condition applied to each element

import numpy as np

arr1 = np.array([1, 2 ,3 ,4 ,10])
arr2 = np.array([0, 3, 3, 2,7])
print(arr1 < arr2)

[False  True False False False]


In [42]:
# Conditional operators - np.where

import numpy as np

print("\nArray 1")
arr1 = np.array([1, 2 ,3 ,4 ,10])
print(arr1)

print("\nArray 2")
arr2 = np.array([0, 3, 3, 2,7])
print(arr2)

print("\nArray 3")
arr3 = np.where(arr2 > arr1, 1, 0)
print(arr3)
    


Array 1
[ 1  2  3  4 10]

Array 2
[0 3 3 2 7]

Array 3
[0 1 0 0 0]


In [49]:
import numpy as np

# Application of conditional operators to null invalid data

print("\nArray 1")
arr1 = (np.random.randn(5,5)*10).astype(np.int8)
print(arr1)

print("\nSet all negative entries to a no data value (e.g. 0)\n")
arr_positive = np.where(arr1 > 0, arr1,  0)
print(arr_positive)



Array 1
[[ -7  14  -9  -6 -15]
 [ -1   1  -3  -3  -1]
 [-21  -6   7 -14   3]
 [-11   2 -15  -5   9]
 [ -3  -3 -11  -4  -4]]

Set all negative entries to a no data value (e.g. 0)

[[ 0 14  0  0  0]
 [ 0  1  0  0  0]
 [ 0  0  7  0  3]
 [ 0  2  0  0  9]
 [ 0  0  0  0  0]]


In [9]:
# Logical operators - masking data

import numpy as np

mask1 = np.array([ [1, 1, 1, 1, 1], 
          [0, 0, 0, 1, 1],
          [0, 0, 0, 1, 1],
          [0, 0, 0, 0, 1],
          [0, 0, 0, 0, 0]
        ])

print("\nmask1")
print(mask1)

print("\nLogical Not")
not_mask1 = np.logical_not(mask1)
print(not_mask1)


mask2 = np.array([ [0, 0, 0, 0, 0], 
          [0, 0, 0, 0, 0],
          [0, 0, 0, 1, 1],
          [0, 0, 0, 1, 0],
          [1, 1, 1, 1, 1]])

print("\nmask2")
print(mask2)


print("\nLogical and")
mask3 = np.logical_and(mask1, mask2)
print("\nmask3")
print(mask3)


print("\nLogical or")
mask4 = np.logical_or(mask1, mask2)
print("\nmask4")
print(mask4)

print("\nNested conditions")
print("\nmask5")
mask5 = np.logical_not(np.logical_or(mask1, mask2))
print(mask5)


mask1
[[1 1 1 1 1]
 [0 0 0 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]

Logical Not
[[False False False False False]
 [ True  True  True False False]
 [ True  True  True False False]
 [ True  True  True  True False]
 [ True  True  True  True  True]]

mask2
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]
 [0 0 0 1 0]
 [1 1 1 1 1]]

Logical and

mask3
[[False False False False False]
 [False False False False False]
 [False False False  True  True]
 [False False False False False]
 [False False False False False]]

Logical or

mask4
[[ True  True  True  True  True]
 [False False False  True  True]
 [False False False  True  True]
 [False False False  True  True]
 [ True  True  True  True  True]]

Nested conditions

mask5
[[False False False False False]
 [ True  True  True False False]
 [ True  True  True False False]
 [ True  True  True False False]
 [False False False False False]]


In [10]:
# Exercise: Create array where mask1 is True and mask2 is False
arr = np.logical_and(mask1, np.logical_not(mask2))
print("TEST")
print(arr)

TEST
[[ True  True  True  True  True]
 [False False False  True  True]
 [False False False False False]
 [False False False False  True]
 [False False False False False]]
